version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: sma_db
    ports:
      - 27017:27017

  web:
    build: .
    restart: always
    command: bash -c "
        python3 manage.py shell < seeds.py &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - migration
  
  migration:
    build: 
      context: .
    command: python3 manage.py migrate sma
    volumes:
      - .:/code
    depends_on:
      - mongodb
