# Generated by Django 4.0.4 on 2022-05-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(default='BRLBTC', max_length=6)),
                ('timestamp', models.DateField()),
                ('sma_20', models.FloatField()),
                ('sma_50', models.FloatField()),
                ('sma_200', models.FloatField()),
            ],
        ),
    ]
