# Generated by Django 4.0.4 on 2022-05-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordMissing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('pair', models.CharField(default='BRLBTC', max_length=6)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
